ALTER TABLE locations DROP COLUMN IF EXISTS address;
ALTER TABLE locations ADD COLUMN IF NOT EXISTS street_name  VARCHAR(255);
ALTER TABLE locations ADD COLUMN IF NOT EXISTS street_number VARCHAR(20);
ALTER TABLE locations ADD COLUMN IF NOT EXISTS city          VARCHAR(100);
ALTER TABLE locations ADD COLUMN IF NOT EXISTS postal_code   VARCHAR(20);
ALTER TABLE locations ADD COLUMN IF NOT EXISTS country       VARCHAR(100);
